### ISSUE TITLE
session-file-store emits a ton of warnings

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#115]
should look at why.  might be linked to #71 (why flashes don't show)

see also perhaps https://github.com/valery-barysok/session-file-store/issues/26

**Comment by valery-barysok** [comment]
@takkaria, do you still have this issue?

**Comment by takkaria** [comment]
I have upgraded to version 1.x and I will run the code to see.

**Comment by takkaria** [comment]
Yes, I am.  I get repeated messages of the form

```
[session-file-store] will retry, error on last attempt: Error: ENOENT: no such file or directory, open 'sessions/yxP1kBSNzwr7APfu5FjKTLXfyxnHU8nt.json'
```

This seems to happen 5 times per page, but only sometimes.  I think what might be happening is that the session has expired (and the file deleted) but the code is still looking for the file.

**Comment by valery-barysok** [comment]
@takkaria, did you try suggested approach from valery-barysok/session-file-store#26?

**Comment by takkaria** [comment]
@valery-barysok I never destroy the session in my code, so there is no point at which to clear to cookie.

**Comment by valery-barysok** [comment]
@takkaria, i got. so if session has expired but cookie still exists then it can happen too. did you use reap of stale sessions?

**Comment by takkaria** [comment]
I get a message every now and again saying '[session-file-store] Deleting expired sessions' if that's what you mean?

**Comment by takkaria** [comment]
I guess this is not avoidable, since file-session-store does not keep an index of sessions. I would settle for 0 retries and no error message when a session is not found.
