### ISSUE TITLE
event descriptions need auto-formatting

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#13]
Abolish old-echo's word count and introduce a formatting system such as Markdown.  would be useful to have lists, auto-linked URLs, but not e.g. tables.

**Comment by supervacuo** [comment]
https://www.npmjs.com/package/node-markdown should make this pretty easy? Although I guess a preview would be good (if not a live preview).

Also maybe in favour of a Twitter-style character count if not a word count; handy to know if you've hit a limit, and I think a limit would help prevent people going crazy w/ e.g. tables…?

**Comment by takkaria** [comment]
Node-markdown's GH page suggests it's not maintained and we should use https://github.com/chjj/marked

Yeah, so some kind of maximum count would be fine, maybe only displayed when you're getting near / going over limit?  Mostly the current word count existed to stop Echo's front page getting way too long!
