### ISSUE TITLE
duplicate detection

### ISSUE THREAD

**Issue by supervacuo** [takkaria/echojs#22]
Primarily for manually adding events, but also some kind of helper for deciding what to do about imported events?

There's some [code in the PHP version](https://github.com/takkaria/echo/blob/master/index.php#L222) which does a check for events starting the same day and +/- 1 hour which seems like it might be enough?

**Comment by takkaria** [comment]
Yup, at the moment the PHP version only shows you the duplicate info for imported events.  It would be great to display this to the user when they select a datetime too.

**Comment by supervacuo** [comment]
> It would be great to display this to the user when they select a datetime too.

Sounds like a sensible first step.

> Yup, at the moment the PHP version only shows you the duplicate info for imported events

How / where? Sorry, I guess I could install locally…

**Comment by takkaria** [comment]
It's OK, I wouldn't bother.  It checks for duplicates on every event if you're logged in as an admin/editor and puts them above the admin buttons that appear on most events:

![screen shot 2015-01-15 at 11 13 13](https://cloud.githubusercontent.com/assets/405490/5756447/858c0ba4-9ca7-11e4-8929-825772a8ca4d.png)

**Comment by supervacuo** [comment]
OK, cheers. I wonder if it's worth doing a broader query (or series of queries) to handle e.g. an event which has an "all-day" duplicate (once we have #53) or a duplicate on the following / preceding day. Is it worth trying to do some kind of name-based matching? Not sure how often this comes up.

**Comment by takkaria** [comment]
I was thinking about name-based matching; I think that might be useful one day but not right now (simple date-based dupe checking should be enough given how little data we have).  But totally in favour of (a) wider query/ies.
