### ISSUE TITLE
use bcrypt for password hashing

### ISSUE THREAD

**Issue by supervacuo** [takkaria/echojs#33]
https://github.com/ncb000gt/node.bcrypt.js

I guess this would require resetting all existing user passwords, so may not be worthwhile. But it's probably best to do as little of our own crypto as possible...

Several examples searching GitHub for "bcrypt sequelize", e.g.:

 * [`hawflau/splitbill`](https://github.com/hawflau/splitbill/blob/411772235ae409fffb01957d56367b29081de2ec/app/models/user.js)
 * [`xmkhan/Telegenic`](https://github.com/xmkhan/Telegenic/blob/afe0f2c35dd66975cf63ec50aef1ada2c990beac/models/user.js) ([`login.js` also has a nice example]((https://github.com/xmkhan/Telegenic/blob/afe0f2c35dd66975cf63ec50aef1ada2c990beac/routes/login)) of using [`step()`](https://github.com/creationix/step), which looks a lot neater than callback spaghetti.
 * [`maxidev/tp-node-js`](https://github.com/maxidev/tp-node-js/blob/master/routes/panel.js)

**Comment by takkaria** [comment]
maybe it would make sense to do this sooner rather than later, before this JS version is deployed?  bcrypt seems pretty cool
