### ISSUE TITLE
configuration system

### ISSUE THREAD

**Issue by supervacuo** [takkaria/echojs#44]
Find & implement instance-level config to set e.g. a `hostname` or `domain` or `live_url` or something, so emails can link to `localhost` during development. Will also be useful for DB settings.

Whichever mechanism we pick might also be handy to have a configurable feed list for `bin/fetchfeeds`

**Comment by takkaria** [comment]
Oo you're right about bin/fetchfeeds, existing-echo has this functionality.  #45 opened as a result.

**Comment by supervacuo** [comment]
Possibilities?:

 * [`node-convict`](https://github.com/mozilla/node-convict) (validates against a schema)
* [`dotenv`](https://github.com/motdotla/dotenv) (loads env vars from an .env file, doesn't seem to have built-in support for different envs)
* ['node-config'](https://www.npmjs.com/package/config)
* just `require('config.js')

[SO thread with other suggestions](http://stackoverflow.com/questions/5869216/how-to-store-node-js-deployment-settings-configuration-files)

Preferences?

**Comment by takkaria** [comment]
Hmm, I think I'm leaning towards something minimalistic, like require or dotenv, instead of introducing config files or multiple ways to set config vars.  Dotenv seems pretty straightforward.  What do you think?

**Comment by supervacuo** [comment]
:+1: having a more complicated config system should probably be driven by needs; I can't think of another usecase for the moment & can certainly maintain a 1-line file myself…
