### ISSUE TITLE
admin interface for event approval/rejection

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#5]
- [x] login-protected admin area
 - [ ] admin e-mail notification of new submitted events
 - [x] list of un-actioned events
 - [x] approve / reject views
 - [ ] owner e-mail notification of event rejection / approval
 - [ ] list of rejected events

**Comment by supervacuo** [comment]
- [ ] login-protected admin area
 - [ ] admin e-mail notification of new submitted events
 - [ ] list of un-actioned events
 - [ ] approve / reject views
 - [ ] owner e-mail notification of event rejection / approval
 - [ ] list of rejected events

**Comment by supervacuo** [comment]
* email notification tracked in #12 
 * archive list of "hidden" events is #20 

Anything else need doing here, or can we merge [the `admin` branch](/takkaria/echojs/tree/admin) (which depends on `password-auth` but not `slug_urls`)?

**Comment by takkaria** [comment]
Nice work!  This all looks great :)
