### ISSUE TITLE
client-side form validation

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#51]

**Comment by supervacuo** [comment]
We might want to share validation code between client & server to prevent bugs creeping in (data which the client won't let through but the server will). [`assurance`](https://github.com/danmilon/assurance) and [`revalidator`](https://github.com/flatiron/revalidator) are intended for this; we already use [`validate.js`](http://validatejs.org/) *via* `sequelize` which says it works in both as well (but would mean storing our validators in a file that was accessible to the client).
