### ISSUE TITLE
add session persistence

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#63]
perhaps using [express-sessions](https://www.npmjs.com/package/express-sessions)? doesn't look like there are many prebuilt SQL Express session stores

**Comment by supervacuo** [comment]
Are you working on this? Being logged out of the admin area every time `nodemon` reloads the app is driving me nuts. I did find this `sequelize`-specific session store, by the way: [connect-sequelize](https://www.npmjs.com/package/connect-sequelize)
