### ISSUE TITLE
404s in admin interface

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#95]
doing these things:
• admin> approve event > back to event > 404
• admin> clicking the event number in the crumbtrail

produces a 404, because they link to /admin/<event id> instead of /admin/event/<event id>.

**Comment by supervacuo** [comment]
Both of these links work for me locally (at dd49861); am I missing something or is this fixed?

e.g. both "back to event" & breadcrumb links go to http://localhost:3000/admin/event/587
