### ISSUE TITLE
optimise event approval workflow

### ISSUE THREAD

**Issue by takkaria** [takkaria/echojs#96]
feedback from mel:
 - [x] the events to approve table would be more helpful if it had the beginning of the body rather than the url.
 - [x] when clicking on a specific event to read more details before approving it'd be useful to have the approve/edit/reject buttons there instead of having to go back to main table
 - [x] pretty annoying to ask if im sure I wanna approve...
 - [x] once an event is approved, instead of landing on the event details it'd be great to land on the updated table of events remaining to approve
 - [x] once an event is approved, can admins have a button to delete it pls.

**Comment by supervacuo** [comment]
> once an event is approved, can admins have a button to delete it pls

Is an "un-approve" button (linking to `/reject/`) on the event detail page sufficient for this? Or is there a related request for an "approved events" table in admin?

**Comment by supervacuo** [comment]
>  once an event is approved, instead of landing on the event details it'd be great to land on the updated table of events remaining to approve

This is implemented with the `next` query parameter, e.g. navigating to `/admin/event/633/approve?next=/admin` will show the approval confirmation page, then clicking "Approve" redirects to `/admin`. The default is left as the event detail page as that seemed the hardest to manually specify, otherwise

**Comment by takkaria** [comment]
(oops - sorry for notification spam - I was just seeing if a ticket can have more than one assignee...)

> Is an "un-approve" button (linking to /reject/) on the event detail page sufficient for this?

Yeah I think it's fine.
